# This file is now replaced by the comprehensive CI/CD pipeline in ci-cd.yml
# You can safely delete this file as deployment is handled by the main workflow

# Keeping this as a backup/reference - consider removing after confirming ci-cd.yml works

name: Deploy to Firebase Hosting on merge (DEPRECATED)
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FORTUDO }}'
          channelId: live
          projectId: fortudo
